### ISSUE TITLE
Full user-side support for medal tracking

### ISSUE THREAD

**Issue by ds-sloth** [TheXTech/TheXTech#644]
Some tasks should be completed to make medal tracking fully user-friendly before the 1.3.7 release.

- [ ] Decide whether to enable by default, let's discuss in this issue
- [x] Add documentation to Wiki about medal tracking config option (@ds-sloth)
- [x] Make it possible to set medal indexes in the in-game editor (@ds-sloth)
- [x] Make it possible to set medal indexes in the Moondust editor (@Wohlstand, can you do this? It uses exactly the same fields as the new Star tracking code, except that the maximum index is 8 in TheXTech.)

**Comment by Wohlstand** [comment]
Speaking about medal indexes, that should be enough to extend te TheXTech SDK without changing of the code of Editor itself.

**Comment by LoveBodhi** [comment]
Another Option: Set which NPC for medal.

**Comment by LoveBodhi** [comment]
As for Enable by default: We should let this option to be toggable via `gameinfo.ini`.

**Comment by ds-sloth** [comment]
Good note, gameinfo.ini will work naturally after the Config-Compat update

**Comment by Wohlstand** [comment]
I updated TheXTech SDK, so, now it adds the Medal Index (I set range between 0 and 8).

**Comment by LoveBodhi** [comment]
Can user change the NPC for medals in the future?

**Comment by ds-sloth** [comment]
Possibly after custom NPCs are possible, if there is demand for it.

**Comment by ds-sloth** [comment]
The option is available in the Video settings and off by default (like the fails counter).
