### ISSUE TITLE
Prepare for 1.3.7 release

### ISSUE THREAD

**Issue by Wohlstand** [TheXTech/TheXTech#875]
This is a small list of tasks to finish in order to release 1.3.7

- [x] Make the docker image for homebrew assets.
- [x] Automation of languages sync from main repo to game assets.
- [x] On a quick hand, implement the On-Exit warp event support.
- [x] Try to implement my recent issues on a quick hand (they are pretty simple to implement I suppose):
  - [x] Possible to delay: https://github.com/TheXTech/TheXTech/issues/868
  - [x] https://github.com/TheXTech/TheXTech/issues/867
    - [x] Review and fine tune (if needed) this: https://github.com/TheXTech/TheXTech/issues/867
  - [x] Possible to delay: https://github.com/TheXTech/TheXTech/issues/866
- [ ] **DELAYED**: Try to adjust the behaviour of the checkpoints and hubs logic (additionally, I recently got an idea to add extra settings to manipulate some of behaviour, like, "Use original (default)" and "Use new logic" regarsing behaviour of checkpoint and warp transitions behaviour. Additionally I got an idea of option to adjust behaviour of off-screen exit. For example, Analogue Funk contains an option to "replay cutscenes", but they are broken because of default SMBX's behaviour, even the message box warns that "for unknown reasons, attempts to go here cause you to go into world map", etc. And I could use that to adjust this behaviour at the ported version to let character conditionally return to the hub, or quit to the world map). https://github.com/TheXTech/TheXTech/issues/863
- [ ] **DELAYED** Investigate the PS Vita problem with the viewport and try to fix it. https://github.com/TheXTech/TheXTech/issues/864. Actually, this needs more time to debug this. So, just leave this as a "known issue" for now.
- [ ] **DELAYED** (depends on [this](https://discuss.haiku-os.org/t/package-creation-fails-in-the-cross-compile-docker-container/16079), possibly should be done after resolving that problem) Try to make the CI for Haiku and the production of packages for this platform.
- [ ] Fix several micro-issues discovered by 0lhi while streaming Valtteri's Island - Revisited
  - [x] 4P cheats should not allow invalid mount states
  - [x] Display camera icon in bottom right when vanilla cam is active
  - [x] Fix display of NPC during final fight in Modern Mode
  - [ ] **DELAYED** #879
  - [x] Assertion failure with >2P in warp in Vegetable Valley
  - [x] Possible to get into Options and Controls Menus but not escape them. Found and fixed!
  - [x] Check behavior when playing riding pet mount hits spike block while on a slowly falling block: it's vanilla (and rare, only affecting the level it was caught in).
  - [x] Purple Pet hint should say "Press Alt Run to pound downwards!" instead of "Press to pound downwards!".
    - [x] **Translations must be updated.**
  - [x] Remember which characters the players were when the game was exited (like how the player setup screen currently remembers characters)
- [x] Fix the bug of background-40 rendering (#881)
- [x] Update [TheXTech SDK package](https://github.com/TheXTech/TheXTech-SDK), especially the integrational script to add the support of the new macOS methods.

## Also, more buerocratic tasks:
- [ ] Ensure all the documentation up to date:
  - [x] CMake options
  - [x] Build guildes including package creation:
    - [x] [Linux and xBSD](https://github.com/TheXTech/TheXTech/wiki/Building-on-Linux-or-xBSD)
      - [x] Finalize the [Linux/xBSD packaging guide](https://github.com/TheXTech/TheXTech/wiki/Building-packages-for-Linux-or-xBSD)
    - [x] [Windows](https://github.com/TheXTech/TheXTech/wiki/Building-on-Windows)
    - [x] [macOS](https://github.com/TheXTech/TheXTech/wiki/Building-on-macOS)
    - [x] [Haiku](https://github.com/TheXTech/TheXTech/wiki/Building-on-Haiku)
    - [x] [Emscripten](https://github.com/TheXTech/TheXTech/wiki/Building-on-Emscripten)
    - [x] [Android](https://github.com/TheXTech/TheXTech/wiki/Building-for-Android)
    - [x] [PS Vita](https://github.com/TheXTech/TheXTech/wiki/Building-for-PS-Vita)
    - [x] [Switch](https://github.com/TheXTech/TheXTech/wiki/Building-for-Nintendo-Switch)
    - [x] [3DS](https://github.com/TheXTech/TheXTech/wiki/Building-for-3DS)
    - [x] [Wii](https://github.com/TheXTech/TheXTech/wiki/Building-for-Wii)
    - [x] [Wii U](https://github.com/TheXTech/TheXTech/wiki/Building-for-Wii-U)
  - [x] Update assets installation and usage manuals, ensure they tells properly about updates.
    - [x] [Windows](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Windows)
    - [x] [Linux and xBSD](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Linux-or-xBSD)
    - [x] [macOS](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-macOS)
    - [x] [Android](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Android)
    - [x] [3DS](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-3DS)
    - [x] [Wii](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Wii)
    - [x] [Wii U](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Wii-U)
    - [x] [Switch](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Switch)
    - [x] [Haiku](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-on-Haiku)
    - [x] [Web-Browsers](https://github.com/TheXTech/TheXTech/wiki/Running-game-assets-in-Web-Browser)
  - [x] Update the compat.ini manual and ensure it matches with the current code.
  - [x] Update the gameinfo.ini manual and ensure it matches with the current code.
  - [x] Update the settings/thextech.ini manual and ensure it matches with the current code.
  - [ ] Finish the work (or temporarily remove) the gameplay manual for the "Adventures of Demo" game pack.
  - [x] Actualize the command-line arguments manual since new arguments were added and some old of them were been alternated.
  - [x] Actualize the IPC description since new commands were introduced.
- [ ] Perform after release:
  - [x] Update the [project page](https://wohlsoft.ru/projects/TheXTech/) to show actual guides and add new downloads.

**Comment by ds-sloth** [comment]
I think it's fine to delay #866 and #868, as well as the checkpoints issue.

The checkpoints issue, especially, is complicated and we should spend some time to be certain we have a good solution.

My main focus would be on fixing the Vita viewport issue (if possible), testing #867, and testing the game overall on all of our hardware targets.

**Comment by Wohlstand** [comment]
Checkpoint issue is already delayed, it needs more time and experiments to implement the solution, and as I explained, that will need a kind of opt-in option to specify the behaviour to don't break old.

**Comment by ds-sloth** [comment]
So, I'll mark all of these on the checklist as delayed for now so we can focus on the most immediate issues.

**Comment by Wohlstand** [comment]
The BG2-40 bug is marked as complete, because I fixed it just now, and additionally, it's exclusive to `main`, isn't reproduced at `stable-1.3.7.x`, so. now I focus on "buerocratic" tasks until anything also.

**Comment by Wohlstand** [comment]
About translations:
- Russian from my side had been updated.
- Chinese translation didn't yet updated, there are few lines left unfinished (That's on the side of @LoveBodhi)

**Comment by Wohlstand** [comment]
The manual for packagers is made, but it needs some fine tune and clarification to be named as fully completed: https://github.com/TheXTech/TheXTech/wiki/Building-packages-for-Linux-or-xBSD

**Comment by Wohlstand** [comment]
One biggest thing I forgot is updating the integrational script at the TheXTech SDK to bring the proper support of assets selection new methods. Old script expects app bundles with embedded resources and it doesn't work with the generic executable and assets installed somewhere also.

**Comment by Wohlstand** [comment]
Okay, seems everything except of delayed tasks has been completed. These delayed tasks will be re-assigned into new milestone.
